### ISSUE TITLE
浏览器引入antd后，range-picker中的panelChange无法使用。

### ISSUE THREAD

**Issue by kvsl9** [vueComponent/vue-dash-event#2]
Version
1.3.5

Environment
win10 ,vue 2.6.7

Reproduction link
https://vue.ant.design/components/date-picker-cn/#API

Steps to reproduce
在浏览器引入vue-dash-event.min.js后，openChanage 只能生效一次，panelChange方法不不生效，并且面板上的输入日期不变，请问什么原因？

What is expected?
openChanage ，panelChange 在浏览器引入中使用生效。

What is actually happening?
openChanage 只能生效一次，panelChange方法不不生效，并且面板上的输入日期不变。
 
![image](https://user-images.githubusercontent.com/270284/54178750-c83ff880-44d1-11e9-85dc-7aa3f5ed72d8.png)
![image](https://user-images.githubusercontent.com/270284/54178756-ce35d980-44d1-11e9-809e-cd3eb6747d6e.png)
![image](https://user-images.githubusercontent.com/270284/54178767-d4c45100-44d1-11e9-8e23-6e9683fd4ced.png)

**Comment by tangjinzhou** [comment]
你的value写死了当然不变，你要么通过回调改变，要么使用v-model

**Comment by kvsl9** [comment]
去掉value,handlePanelChange方法还是无法执行。
![image](https://user-images.githubusercontent.com/270284/54201500-c2b1d500-4508-11e9-96c8-6a9ba65acef3.png)
![image](https://user-images.githubusercontent.com/270284/54201523-d52c0e80-4508-11e9-8aa3-4fd59359a7cd.png)

**Comment by kvsl9** [comment]
> 你的value写死了当然不变，你要么通过回调改变，要么使用v-model
去掉value,handlePanelChange方法还是无法执行。
 
![image](https://user-images.githubusercontent.com/270284/54246357-88c7e980-456f-11e9-85e3-ced4342acfc2.png)
![image](https://user-images.githubusercontent.com/270284/54246366-94b3ab80-456f-11e9-9da8-b9f8b8641d5b.png)
